In [2]:
import numpy as np 
import pandas as pd

In [3]:
rowdata = {'颜色深度':[14.23,13.2,13.16,14.37,13.24,12.07,12.43,11.79,12.37,12.04],
          '酒精浓度':[5.64,4.38,5.68,4.80,4.32,2.76,3.94,3.  ,2.12,2.6 ],
          '品种':[0,0,0,0,0,1,1,1,1,1]}
# 0 - 黑皮诺，1 - 赤霞珠
wine_data = pd.DataFrame(rowdata)

wine_data

颜色深度  酒精浓度  品种
0  14.23  5.64   0
1  13.20  4.38   0
2  13.16  5.68   0
3  14.37  4.80   0
4  13.24  4.32   0
5  12.07  2.76   1
6  12.43  3.94   1
7  11.79  3.00   1
8  12.37  2.12   1
9  12.04  2.60   1

In [11]:
X = np.array(wine_data.iloc[:,0:2])   # 提取特征
y = np.array(wine_data.iloc[:,-1])    # 提取标签
X,y 

(array([[14.23,  5.64],
        [13.2 ,  4.38],
        [13.16,  5.68],
        [14.37,  4.8 ],
        [13.24,  4.32],
        [12.07,  2.76],
        [12.43,  3.94],
        [11.79,  3.  ],
        [12.37,  2.12],
        [12.04,  2.6 ]]),
 array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int64))

In [8]:
new_data = np.array([12.8,4.1]) # 新的红酒

In [9]:
import matplotlib.pyplot as plt

In [12]:
X[y==1,0]

array([12.07, 12.43, 11.79, 12.37, 12.04])