In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

In [2]:
a = np.array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]])
a

array([[1. , 1.1],
       [1. , 1. ],
       [0. , 0. ],
       [0. , 0.1]])

In [3]:
a[:, np.newaxis]

array([[[1. , 1.1]],

       [[1. , 1. ]],

       [[0. , 0. ]],

       [[0. , 0.1]]])

In [5]:
[[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]]

[[1.0, 1.1], [1.0, 1.0], [0, 0], [0, 0.1]]

In [6]:
np.array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]])

array([[1. , 1.1],
       [1. , 1. ],
       [0. , 0. ],
       [0. , 0.1]])