# 查看版本的信息

In [1]:
import numpy as np

In [3]:
np.__version__  #查看版本信息

'1.16.2'

# 数组属性

In [9]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [8]:
type(a) #查看类型

numpy.ndarray

In [10]:
a.ndim #维度

1

In [11]:
a.T  #转置，一维的数组不分行和列

array([1, 2, 3, 4, 5])

In [12]:
a.shape #形状

(5,)

In [15]:
b=np.array([[1,2],[3,4]]) #二维数组
b

array([[1, 2],
       [3, 4]])

In [23]:
d=np.array([[1,2],[3,4,5]]) 
d.shape

(2,)

In [24]:
d.dtype

dtype('O')

In [16]:
b.shape

(2, 2)

In [20]:
c=np.array([[[1,2],[3,4]]]) #三维数组
c

array([[[1, 2],
        [3, 4]]])

In [21]:
c.shape

(1, 2, 2)

In [22]:
c.ndim #维度

3

In [18]:
b.size

4

In [19]:
b.itemsize

4

In [17]:
b.ndim 

2

In [18]:
a.T.shape

(5,)

In [19]:
a.size

5

In [13]:
a.dtype #数据类型

dtype('int32')

In [22]:
a.itemsize #元素的大小，字节为单位，8个位为一个字节

4

In [26]:
c=np.array([1,2.1,3,4,5])
c

array([1. , 2.1, 3. , 4. , 5. ])

In [27]:
c.dtype

dtype('float64')

In [27]:
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [28]:
b.ndim #维度

2

In [29]:
b.shape

(2, 2)

In [30]:
b.size #元素数量

4

In [31]:
b.dtype #数据类型

dtype('int32')

In [32]:
b.itemsize #元素大小

4

扩展顺序：布尔值，int,float,complex

# 数组的创建

## 数组内置方法

In [29]:
np.arange(10) #左闭右开

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0,10,2) #左闭右开,开始，结束，步长

array([0, 2, 4, 6, 8])

In [31]:
np.linspace(0,10,11)#等差数组，两边闭合，开始，结束，元素个数,  间隔 (10-0)/(11-1)= 1.0

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
np.linspace(0,10,21) #0.5间隔

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [24]:
np.logspace(0,100,11) #等比数组，默认以10为底

array([1.e+000, 1.e+010, 1.e+020, 1.e+030, 1.e+040, 1.e+050, 1.e+060,
       1.e+070, 1.e+080, 1.e+090, 1.e+100])

In [26]:
np.logspace(1,6,6,base=2) #2为底

array([ 2.,  4.,  8., 16., 32., 64.])

In [34]:
np.zeros(3) #全零数组,3是shape

array([0., 0., 0.])

In [35]:
np.zeros((3,3)) #(3,3)是shape

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.ones((4,4)) #二维全1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
d=np.ones((5,3,4)) #三维数组
d.shape

(5, 3, 4)

In [38]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) 
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
d.shape

(2, 2, 3)

In [40]:
c=np.array([[1,2],[3.1,4]]) #二维的列表
c.shape

(2, 2)

In [41]:
c

array([[1. , 2. ],
       [3.1, 4. ]])

In [42]:
np.zeros_like(c) #和c的形状一样，全0

array([[0., 0.],
       [0., 0.]])

In [50]:
np.ones_like(c) #和c的形状一样，全1

array([[1., 1.],
       [1., 1.]])

In [43]:
10*np.ones_like(c)

array([[10., 10.],
       [10., 10.]])

In [44]:
np.full((3,3),8) #全为8的数组

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [53]:
np.identity(4)#单位数组

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
np.eye(4)#单位数组

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
a=np.diag([1,2,3,4]) #对角数组
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [52]:
np.fliplr(a)  #反向对角数组

array([[0, 0, 0, 1],
       [0, 0, 2, 0],
       [0, 3, 0, 0],
       [4, 0, 0, 0]])

In [47]:
np.diag([1,2,3,4],k=-1) #对角数组

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [49]:
np.empty((3,3)) #空数组，元素值不确定

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## 随机数产生

In [58]:
np.random.randint(0,50,5) #随机整数，包括0，不包括50

array([29, 24, 34,  4, 41])

In [55]:
np.random.randint(0,1,5) #随机整数,不包括1

array([0, 0, 0, 0, 0])

In [60]:
np.random.rand(5) #[0, 1)之间的均匀分布浮点数,随机值

array([0.04627256, 0.98176521, 0.30668083, 0.46815599, 0.72172478])

In [62]:
np.random.rand(2,2) #二维数组

array([[0.99551885, 0.01347482],
       [0.25271596, 0.42714768]])

In [61]:
np.random.random(5)#返回随机的浮点数，在半开区间 [0.0, 1.0)。

array([0.19753225, 0.01822944, 0.3242216 , 0.55153039, 0.36535369])

In [92]:
np.random.random((2,2)) #二维数组，元组的形式

array([[0.24429087, 0.79508747],
       [0.35209494, 0.63887768]])

In [86]:
np.random.seed(1000000000)  #固定种子，随机数生成
np.random.rand(5)  #[0, 1)之间的均匀分布浮点数,随机值

array([0.84172754, 0.54416454, 0.86253081, 0.10171506, 0.65258716])

In [87]:
np.random.seed(5)  #固定种子，随机数生成
np.random.rand(5)  #[0, 1)之间的均匀分布浮点数,随机值

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119])

In [14]:
np.random.randn(5) #标准正态分布，均值为0，方差为1

array([ 0.4346417 ,  0.60279313, -1.6061894 , -1.13878002,  0.5746296 ])

In [70]:
np.random.standard_normal(5) #标准正态分布

array([-0.66437971, -0.60555494, -0.65099088,  0.51256776,  0.26238882])

In [88]:
np.random.normal(1,5,10) #均值，标准差，shape

array([ 7.83792762,  3.87353844, -8.42881204,  1.85462684, -1.01546656,
        9.18814245, -2.02648924, -6.97207537,  5.55936821, -6.21920777])

In [90]:
np.random.normal(1,5,(4,4)) #均值，标准差，shape

array([[ 7.14442038, -0.97915629,  8.62512956,  2.3078511 ],
       [-1.43750451,  0.92199729,  6.6683347 ,  3.35866106],
       [10.84316889,  5.80551479, -0.2684649 , -2.7044529 ],
       [ 1.26032077, -1.60830357, -1.47118473, -4.71919991]])

# 数组数据类型

In [94]:
a=np.array([1,2.1,3,4,5])
a

array([1. , 2.1, 3. , 4. , 5. ])

In [80]:
1+2.0  #扩展顺序：布尔值，int,float,complex

3.0

数据类型转换

In [95]:
np.float64(5)

5.0

In [96]:
np.float64(5).dtype

dtype('float64')

In [97]:
np.int32(5.9001) #浮点型转换为整型，直接去掉小数部分

5

In [89]:
np.bool(0.000000000001) #只要不为零，都为True

True

In [91]:
np.bool(0)

False

In [92]:
np.float(True)

1.0

In [99]:
a=np.array([1,2,3])
a.dtype

dtype('int32')

In [100]:
b=a.astype(np.float64)    #转换为想要的数据类型,这个用得比较多
b.dtype

dtype('float64')

In [114]:
a=np.array([2,2,2]).astype(np.int64)  
a.dtype

dtype('int64')

In [115]:
a**31

array([2147483648, 2147483648, 2147483648], dtype=int64)

# 缺失值

In [119]:
a=np.nan
a

nan

In [117]:
type(a) #特殊的浮点数

float

In [118]:
np.isnan(a)#对缺失值进行判断

True

In [120]:
a==np.nan     #不能这样进行判断

False

In [121]:
np.nan==np.nan

False

In [122]:
np.nan-np.nan

nan

In [123]:
2+np.nan

nan

In [124]:
a1=np.array([1,2,3,np.nan])
np.isnan(a1)

array([False, False, False,  True])

In [125]:
a1.dtype  #np.nan为浮点型，会把所有整型转换为浮点型

dtype('float64')

# 数组元素的索引

## 一维数组索引

In [153]:
a=np.random.rand(5)
a

array([0.84355497, 0.34602815, 0.10082727, 0.38340907, 0.5103548 ])

In [154]:
a[0]

0.8435549661102237

In [128]:
a[4]

0.11169242718357142

In [129]:
a[-1]

0.11169242718357142

In [130]:
a[0:2]  #左闭右开

array([0.49341505, 0.58349974])

In [131]:
a

array([0.49341505, 0.58349974, 0.93929935, 0.94354008, 0.11169243])

In [132]:
a[0:4:2]  #开始，结束，步长

array([0.49341505, 0.93929935])

In [133]:
a[0:-1:2]

array([0.49341505, 0.93929935])

In [134]:
a[0::2]

array([0.49341505, 0.93929935, 0.11169243])

In [135]:
a[:4]

array([0.49341505, 0.58349974, 0.93929935, 0.94354008])

In [136]:
a[2:]

array([0.93929935, 0.94354008, 0.11169243])

In [137]:
a

array([0.49341505, 0.58349974, 0.93929935, 0.94354008, 0.11169243])

In [138]:
a[4:0:-2]#反着取

array([0.11169243, 0.93929935])

In [139]:
a[::-1]#反转数组

array([0.11169243, 0.94354008, 0.93929935, 0.58349974, 0.49341505])

## 多维数组的索引

In [142]:
a=np.array([[1, 2, 3, 4, 5],[4, 5, 6, 7, 8], [7, 8, 9, 10, 11]])
a

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 7,  8,  9, 10, 11]])

In [143]:
a[0,3:5] #索引第0行，3,4列

array([4, 5])

In [117]:
a[1:,2:]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [118]:
a[::2,::2]

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [152]:
a[(0,0,1,1),(1,2,3,4)]#花式索引

array([2, 3, 7, 8])

In [125]:
a[0,(0,2,3,4)]

array([1, 3, 4, 5])

In [145]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [146]:
d.shape #三个轴，分别为0轴，1轴，2轴，

(2, 2, 3)

In [147]:
d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [148]:
d[1][0,1:]  #方法1：三维拆成二维，用二维选择方法

array([8, 9])

In [149]:
d[1,0,1:]   #方法2：三维直接选择

array([8, 9])

In [158]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [150]:
d[:,0,1]      #选出2,8

array([2, 8])

# 变换数组的形态

## 变换数组的形态-reshape,resize

### reshape

In [179]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [180]:
a.shape

(12,)

In [184]:
a.reshape(4,3) #新生成

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [194]:
c=a.reshape(2,2,3) #新生成
c.shape

(2, 2, 3)

In [195]:
c.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [158]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [163]:
b=a.reshape(6,2) #新生成操作，元素总数要一致,不一致则报错

In [160]:
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [164]:
a.reshape(3,2,2) #3维数组

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [168]:
a=np.arange(198)
a.reshape(3,-1) #3行，列自动计算，198/3,要求整除

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
        118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
        131],
       [132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
        145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
        158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
        171, 172, 173, 

In [203]:
a.reshape(-1,3)#3列，行自动计算

array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [ 12,  13,  14],
       [ 15,  16,  17],
       [ 18,  19,  20],
       [ 21,  22,  23],
       [ 24,  25,  26],
       [ 27,  28,  29],
       [ 30,  31,  32],
       [ 33,  34,  35],
       [ 36,  37,  38],
       [ 39,  40,  41],
       [ 42,  43,  44],
       [ 45,  46,  47],
       [ 48,  49,  50],
       [ 51,  52,  53],
       [ 54,  55,  56],
       [ 57,  58,  59],
       [ 60,  61,  62],
       [ 63,  64,  65],
       [ 66,  67,  68],
       [ 69,  70,  71],
       [ 72,  73,  74],
       [ 75,  76,  77],
       [ 78,  79,  80],
       [ 81,  82,  83],
       [ 84,  85,  86],
       [ 87,  88,  89],
       [ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 100, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124

### resize

In [185]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [186]:
a.resize(3,4) #原地修改，返回值为空

In [187]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 展平

### flatten

In [189]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [190]:
a.flatten() #展平，降维，按照行展平,多维变成一维

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [224]:
a.reshape(1,12)# 二维，没有降维

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [15]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [225]:
a.flatten('F')#竖着拼

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

### ravel

In [191]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [192]:
a.ravel() #展平

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 转置（T，swapaxes）

In [196]:
a=np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [197]:
a.T #转置

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [228]:
a.swapaxes(0,1) #交换轴

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [198]:
a=np.arange(24).reshape(4,2,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [200]:
a.swapaxes(1,2) #交换轴

array([[[ 0,  3],
        [ 1,  4],
        [ 2,  5]],

       [[ 6,  9],
        [ 7, 10],
        [ 8, 11]],

       [[12, 15],
        [13, 16],
        [14, 17]],

       [[18, 21],
        [19, 22],
        [20, 23]]])

In [5]:
a.swapaxes(0,1) #交换轴

array([[[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]]])

## 堆叠

### stack

In [201]:
a=np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [202]:
b=a*2
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [251]:
np.hstack((a,b)) #横向堆叠，行数要一致

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22]])

In [159]:
np.vstack((a,b))#纵向堆叠

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

### concatenate

In [253]:
np.concatenate((a,b),axis=0)#上下方向拼接，沿着0轴的方向拼接

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [203]:
np.concatenate((a,b),axis=1)#左右，横向拼接，沿着1轴的方向拼接

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22]])

## 分割

### split

In [205]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [206]:
c=np.vsplit(a,2)  #纵向分割，等分
c

[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [207]:
c[1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [208]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [215]:
np.hsplit(a,3)[0].shape  #横向分割，要能等分

(4, 1)

In [212]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [213]:
np.split(a,2,axis=0)  #0轴这个方向分，上下分

[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [269]:
np.split(a,3,axis=1)  #1轴方向分割，左右分

[array([[0],
        [3],
        [6],
        [9]]), array([[ 1],
        [ 4],
        [ 7],
        [10]]), array([[ 2],
        [ 5],
        [ 8],
        [11]])]

# 数组的运算

## 数组与数值的运算

In [216]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [217]:
a*2  #数组中的每一个元素都乘2，通用函数

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [218]:
a+10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [222]:
a//2 #整除

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5],
       [6, 6, 7, 7]], dtype=int32)

In [221]:
a%2 #求余

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

## 数组与数组的运算

### 数组的shape一样情况

In [225]:
a=np.arange(16).reshape(4,4)
b=np.ones(16).reshape(4,4)

In [228]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [226]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [227]:
a+b #数组的shape一样，对应位置的元素进行操作

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

In [229]:
a*b

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [232]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [233]:
a**a  #溢出，计算结果错误

array([[          1,           1,           4,          27],
       [        256,        3125,       46656,      823543],
       [   16777216,   387420489,  1410065408,  1843829075],
       [ -251658240, -1692154371, -1282129920,  1500973039]], dtype=int32)

In [235]:
a=np.arange(16).reshape(4,4).astype('int64') #用更长的位数表示数据
a**a 

array([[                 1,                  1,                  4,
                        27],
       [               256,               3125,              46656,
                    823543],
       [          16777216,          387420489,        10000000000,
              285311670611],
       [     8916100448256,    302875106592253,  11112006825558016,
        437893890380859375]], dtype=int64)

### 数组的shape不一样

#### 一维数组的广播机制

In [236]:
a=np.array([[0,0,0],[1,1,1],[2,2,3]])
a

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 3]])

In [237]:
b=np.array([1,2,3])
b

array([1, 2, 3])

In [238]:
b.shape

(3,)

In [239]:
a+b

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 6]])

#### 二维数组的广播

In [240]:
a=np.array([[0,0,0],[1,1,1],[2,2,3]])
b=np.array([1,2,3]).reshape(3,1)
a

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 3]])

In [241]:
b

array([[1],
       [2],
       [3]])

In [297]:
a+b

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 6]])

In [243]:
a=np.array([[0,0,0],[1,1,1],[2,2,3]])
b=np.array([1,2,3,4]).reshape(4,1)
a+b  #不满足第三个条件

ValueError: operands could not be broadcast together with shapes (3,3) (4,1) 

In [307]:
a.shape

(3, 3)

In [308]:
b.shape

(4, 1)

In [244]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4]).reshape(4,1)

In [247]:
b

array([[1],
       [2],
       [3],
       [4]])

In [245]:
a.shape

(4,)

In [246]:
b.shape

(4, 1)

In [305]:
a+b

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

判断能否计算：shape补齐后，两个对应轴的长度要么一致，要么为1,才能进行计算