### 导入必要的库

In [1]:
import numpy as np
import pandas as pd

###  导入数据集

In [132]:
data = pd.read_table('snack.csv')
data.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

### 查看前10行内容

In [9]:
data.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

In [8]:
data.tail()  # 查看后五行

order_id  quantity           item_name  \
4617      1833         1       Steak Burrito   
4618      1833         1       Steak Burrito   
4619      1834         1  Chicken Salad Bowl   
4620      1834         1  Chicken Salad Bowl   
4621      1834         1  Chicken Salad Bowl   

                                     choice_description item_price  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75   
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75

In [12]:
data[:10]

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   
6         3         1                          Side of Chips   
7         4         1                          Steak Burrito   
8         4         1                       Steak Soft Tacos   
9         5         1                          Steak Burrito   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98   
6                                                NaN     $1.69   
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75   
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25   
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25

In [15]:
data.iloc[:5,:2]

order_id  quantity
0         1         1
1         1         1
2         1         1
3         1         1
4         2         2

###  数据集中有多少个列(columns)

In [16]:
data.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   order_id            4622 non-null   int64 
 1   quantity            4622 non-null   int64 
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB


In [19]:
data.shape

(4622, 5)

In [18]:
data.shape[1]

5

### 打印出全部的列名称

In [20]:
data.columns  # 查看

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [29]:
# 提取名字
for i in data.columns:
    print(data[i].values)

[   1    1    1 ... 1834 1834 1834]
[1 1 1 ... 1 1 1]
['Chips and Fresh Tomato Salsa' 'Izze' 'Nantucket Nectar' ...
 'Chicken Salad Bowl' 'Chicken Salad Bowl' 'Chicken Salad Bowl']
[nan '[Clementine]' '[Apple]' ...
 '[Fresh Tomato Salsa, [Fajita Vegetables, Pinto Beans, Guacamole, Lettuce]]'
 '[Fresh Tomato Salsa, [Fajita Vegetables, Lettuce]]'
 '[Fresh Tomato Salsa, [Fajita Vegetables, Pinto Beans, Lettuce]]']
['$2.39 ' '$3.39 ' '$3.39 ' ... '$11.25 ' '$8.75 ' '$8.75 ']


In [22]:
data.columns.values

array(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'], dtype=object)

### 数据集的索引是怎样的

In [24]:
data.index.values

array([   0,    1,    2, ..., 4619, 4620, 4621])

### 被购买的数量最多商品(item)是什么?

In [31]:
data.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

In [57]:
data.groupby('item_name')['quantity'].count().sort_values(ascending=False)

item_name
Chicken Bowl                             726
Chicken Burrito                          553
Chips and Guacamole                      479
Steak Burrito                            368
Canned Soft Drink                        301
Steak Bowl                               211
Chips                                    211
Bottled Water                            162
Chicken Soft Tacos                       115
Chicken Salad Bowl                       110
Chips and Fresh Tomato Salsa             110
Canned Soda                              104
Side of Chips                            101
Veggie Burrito                            95
Barbacoa Burrito                          91
Veggie Bowl                               85
Carnitas Bowl                             68
Barbacoa Bowl                             66
Carnitas Burrito                          59
Steak Soft Tacos                          55
6 Pack Soft Drink                         54
Chips and Tomatillo Red Chili Salsa       48


In [54]:
data.groupby(['item_name','order_id']).count()

quantity  choice_description  item_price
item_name         order_id                                          
6 Pack Soft Drink 129              1                   1           1
                  148              1                   1           1
                  154              1                   1           1
                  168              1                   1           1
                  182              1                   1           1
...                              ...                 ...         ...
Veggie Soft Tacos 567              1                   1           1
                  688              1                   1           1
                  948              1                   1           1
                  1132             1                   1           1
                  1559             1                   1           1

[4292 rows x 3 columns]

### 在item_name这一列中，一共有多少种商品被下单？

In [58]:
data.groupby('item_name')['quantity'].count().sort_values(ascending=False)

item_name
Chicken Bowl                             726
Chicken Burrito                          553
Chips and Guacamole                      479
Steak Burrito                            368
Canned Soft Drink                        301
Steak Bowl                               211
Chips                                    211
Bottled Water                            162
Chicken Soft Tacos                       115
Chicken Salad Bowl                       110
Chips and Fresh Tomato Salsa             110
Canned Soda                              104
Side of Chips                            101
Veggie Burrito                            95
Barbacoa Burrito                          91
Veggie Bowl                               85
Carnitas Bowl                             68
Barbacoa Bowl                             66
Carnitas Burrito                          59
Steak Soft Tacos                          55
6 Pack Soft Drink                         54
Chips and Tomatillo Red Chili Salsa       48


In [59]:
len(data.item_name.value_counts())

50

In [63]:
data.item_name.value_counts().shape[0]

50

In [65]:
data.item_name.nunique()

50

### 在choice_description中，下单次数最多的商品是什么？

In [84]:
data.groupby(['choice_description','item_name'])['order_id'].count().sort_values(ascending=False)

choice_description                                                                                              item_name          
[Coke]                                                                                                          Canned Soft Drink      102
[Diet Coke]                                                                                                     Canned Soft Drink       95
[Sprite]                                                                                                        Canned Soft Drink       55
[Lemonade]                                                                                                      Canned Soft Drink       31
[Coca Cola]                                                                                                     Canned Soda             26
                                                                                                                                      ... 
[Tomatillo Green Chili Salsa, [Bla

### 一共有多少商品被下单？

In [87]:
data.shape

(4622, 5)

In [93]:
np.sum(data.groupby('item_name')['order_id'].count())

4622

In [95]:
np.sum(data.quantity)

4972

In [94]:
np.sum(data.groupby('item_name')['quantity'].sum())

4972

### 将item_price转换为浮点数

In [96]:
data.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [98]:
data.item_price.dtype

dtype('O')

In [99]:
for i in data.columns:  # 遍历出所有列名
    if data[i].dtype == 'O':  # 判断数据类型是字符型
        print(i)    # 打印字符型的特征

item_name
choice_description
item_price


In [106]:
data.item_price[0][1:-1]

'2.39'

In [108]:
data.item_price[0].strip('$ ')

'2.39'

In [149]:
def trans(x):
    x = x.strip('$ ')
    return x

In [150]:
data.item_price.apply(trans)

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...  
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: object

In [119]:
# data.item_price = data.item_price.apply(lambda x : x.strip('$ '))

In [153]:
data.item_price = data.item_price.str.strip('$ ').astype(float)

In [154]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   order_id            4622 non-null   int64  
 1   quantity            4622 non-null   int64  
 2   item_name           4622 non-null   object 
 3   choice_description  3376 non-null   object 
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 180.7+ KB


### 在该数据集对应的时期内，收入(revenue)是多少

In [155]:
data.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description  item_price  
0                                                NaN        2.39  
1                                       [Clementine]        3.39  
2                                            [Apple]        3.39  
3                                                NaN        2.39  
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98

In [160]:
revenue = (data.quantity * data.item_price).sum()
revenue

39237.02

### 在该数据集对应的时期内，一共有多少订单？

In [161]:
data.order_id.value_counts()

926     23
1483    14
205     12
691     11
1786    11
        ..
105      1
702      1
718      1
568      1
800      1
Name: order_id, Length: 1834, dtype: int64

In [162]:
data.order_id.nunique()

1834

### 每一单(order)对应的平均总价是多少？

In [163]:
revenue/data.order_id.nunique()

21.39423118865867